/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuthProvidersRouteImport } from './routes/_authenticated/auth-providers'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAgentProfilesRouteImport } from './routes/_authenticated/agent-profiles'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedAdminSecretsRouteImport } from './routes/_authenticated/admin/secrets'
import { Route as AuthenticatedAdminGroupsIndexRouteImport } from './routes/_authenticated/admin/groups/index'
import { Route as AuthenticatedWorkflowsWorkflowIdRequestsRouteImport } from './routes/_authenticated/workflows/$workflowId.requests'
import { Route as AuthenticatedWorkflowsWorkflowIdEditRouteImport } from './routes/_authenticated/workflows/$workflowId.edit'
import { Route as AuthenticatedProjectsProjectIdSecretsRouteImport } from './routes/_authenticated/projects/$projectId.secrets'
import { Route as AuthenticatedProjectsProjectIdMembersRouteImport } from './routes/_authenticated/projects/$projectId.members'
import { Route as AuthenticatedProjectsProjectIdKnowledgeRouteImport } from './routes/_authenticated/projects/$projectId.knowledge'
import { Route as AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRouteImport } from './routes/_authenticated/workflows/$workflowId.requests.$requestId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthProvidersRoute =
  AuthenticatedAuthProvidersRouteImport.update({
    id: '/auth-providers',
    path: '/auth-providers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentProfilesRoute =
  AuthenticatedAgentProfilesRouteImport.update({
    id: '/agent-profiles',
    path: '/agent-profiles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSecretsRoute =
  AuthenticatedAdminSecretsRouteImport.update({
    id: '/admin/secrets',
    path: '/admin/secrets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGroupsIndexRoute =
  AuthenticatedAdminGroupsIndexRouteImport.update({
    id: '/admin/groups/',
    path: '/admin/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsWorkflowIdRequestsRoute =
  AuthenticatedWorkflowsWorkflowIdRequestsRouteImport.update({
    id: '/workflows/$workflowId/requests',
    path: '/workflows/$workflowId/requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsWorkflowIdEditRoute =
  AuthenticatedWorkflowsWorkflowIdEditRouteImport.update({
    id: '/workflows/$workflowId/edit',
    path: '/workflows/$workflowId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdSecretsRoute =
  AuthenticatedProjectsProjectIdSecretsRouteImport.update({
    id: '/$projectId/secrets',
    path: '/$projectId/secrets',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsProjectIdMembersRoute =
  AuthenticatedProjectsProjectIdMembersRouteImport.update({
    id: '/$projectId/members',
    path: '/$projectId/members',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsProjectIdKnowledgeRoute =
  AuthenticatedProjectsProjectIdKnowledgeRouteImport.update({
    id: '/$projectId/knowledge',
    path: '/$projectId/knowledge',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute =
  AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => AuthenticatedWorkflowsWorkflowIdRequestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent-profiles': typeof AuthenticatedAgentProfilesRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/auth-providers': typeof AuthenticatedAuthProvidersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/models': typeof AuthenticatedModelsRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/tools': typeof AuthenticatedToolsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/secrets': typeof AuthenticatedAdminSecretsRoute
  '/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/projects/$projectId/knowledge': typeof AuthenticatedProjectsProjectIdKnowledgeRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/secrets': typeof AuthenticatedProjectsProjectIdSecretsRoute
  '/workflows/$workflowId/edit': typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  '/workflows/$workflowId/requests': typeof AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren
  '/admin/groups/': typeof AuthenticatedAdminGroupsIndexRoute
  '/workflows/$workflowId/requests/$requestId': typeof AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent-profiles': typeof AuthenticatedAgentProfilesRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/auth-providers': typeof AuthenticatedAuthProvidersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/models': typeof AuthenticatedModelsRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/tools': typeof AuthenticatedToolsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/secrets': typeof AuthenticatedAdminSecretsRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/projects/$projectId/knowledge': typeof AuthenticatedProjectsProjectIdKnowledgeRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/secrets': typeof AuthenticatedProjectsProjectIdSecretsRoute
  '/workflows/$workflowId/edit': typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  '/workflows/$workflowId/requests': typeof AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren
  '/admin/groups': typeof AuthenticatedAdminGroupsIndexRoute
  '/workflows/$workflowId/requests/$requestId': typeof AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agent-profiles': typeof AuthenticatedAgentProfilesRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/auth-providers': typeof AuthenticatedAuthProvidersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/admin/secrets': typeof AuthenticatedAdminSecretsRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/_authenticated/projects/$projectId/knowledge': typeof AuthenticatedProjectsProjectIdKnowledgeRoute
  '/_authenticated/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/_authenticated/projects/$projectId/secrets': typeof AuthenticatedProjectsProjectIdSecretsRoute
  '/_authenticated/workflows/$workflowId/edit': typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  '/_authenticated/workflows/$workflowId/requests': typeof AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren
  '/_authenticated/admin/groups/': typeof AuthenticatedAdminGroupsIndexRoute
  '/_authenticated/workflows/$workflowId/requests/$requestId': typeof AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agent-profiles'
    | '/agents'
    | '/auth-providers'
    | '/dashboard'
    | '/knowledge'
    | '/models'
    | '/projects'
    | '/tools'
    | '/users'
    | '/admin/secrets'
    | '/workflows/'
    | '/projects/$projectId/knowledge'
    | '/projects/$projectId/members'
    | '/projects/$projectId/secrets'
    | '/workflows/$workflowId/edit'
    | '/workflows/$workflowId/requests'
    | '/admin/groups/'
    | '/workflows/$workflowId/requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agent-profiles'
    | '/agents'
    | '/auth-providers'
    | '/dashboard'
    | '/knowledge'
    | '/models'
    | '/projects'
    | '/tools'
    | '/users'
    | '/admin/secrets'
    | '/workflows'
    | '/projects/$projectId/knowledge'
    | '/projects/$projectId/members'
    | '/projects/$projectId/secrets'
    | '/workflows/$workflowId/edit'
    | '/workflows/$workflowId/requests'
    | '/admin/groups'
    | '/workflows/$workflowId/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agent-profiles'
    | '/_authenticated/agents'
    | '/_authenticated/auth-providers'
    | '/_authenticated/dashboard'
    | '/_authenticated/knowledge'
    | '/_authenticated/models'
    | '/_authenticated/projects'
    | '/_authenticated/tools'
    | '/_authenticated/users'
    | '/_authenticated/admin/secrets'
    | '/_authenticated/workflows/'
    | '/_authenticated/projects/$projectId/knowledge'
    | '/_authenticated/projects/$projectId/members'
    | '/_authenticated/projects/$projectId/secrets'
    | '/_authenticated/workflows/$workflowId/edit'
    | '/_authenticated/workflows/$workflowId/requests'
    | '/_authenticated/admin/groups/'
    | '/_authenticated/workflows/$workflowId/requests/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auth-providers': {
      id: '/_authenticated/auth-providers'
      path: '/auth-providers'
      fullPath: '/auth-providers'
      preLoaderRoute: typeof AuthenticatedAuthProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-profiles': {
      id: '/_authenticated/agent-profiles'
      path: '/agent-profiles'
      fullPath: '/agent-profiles'
      preLoaderRoute: typeof AuthenticatedAgentProfilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/secrets': {
      id: '/_authenticated/admin/secrets'
      path: '/admin/secrets'
      fullPath: '/admin/secrets'
      preLoaderRoute: typeof AuthenticatedAdminSecretsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/groups/': {
      id: '/_authenticated/admin/groups/'
      path: '/admin/groups'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AuthenticatedAdminGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/$workflowId/requests': {
      id: '/_authenticated/workflows/$workflowId/requests'
      path: '/workflows/$workflowId/requests'
      fullPath: '/workflows/$workflowId/requests'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/$workflowId/edit': {
      id: '/_authenticated/workflows/$workflowId/edit'
      path: '/workflows/$workflowId/edit'
      fullPath: '/workflows/$workflowId/edit'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/secrets': {
      id: '/_authenticated/projects/$projectId/secrets'
      path: '/$projectId/secrets'
      fullPath: '/projects/$projectId/secrets'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSecretsRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$projectId/members': {
      id: '/_authenticated/projects/$projectId/members'
      path: '/$projectId/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMembersRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$projectId/knowledge': {
      id: '/_authenticated/projects/$projectId/knowledge'
      path: '/$projectId/knowledge'
      fullPath: '/projects/$projectId/knowledge'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdKnowledgeRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/workflows/$workflowId/requests/$requestId': {
      id: '/_authenticated/workflows/$workflowId/requests/$requestId'
      path: '/$requestId'
      fullPath: '/workflows/$workflowId/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedWorkflowsWorkflowIdRequestsRoute
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdKnowledgeRoute: typeof AuthenticatedProjectsProjectIdKnowledgeRoute
  AuthenticatedProjectsProjectIdMembersRoute: typeof AuthenticatedProjectsProjectIdMembersRoute
  AuthenticatedProjectsProjectIdSecretsRoute: typeof AuthenticatedProjectsProjectIdSecretsRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdKnowledgeRoute:
    AuthenticatedProjectsProjectIdKnowledgeRoute,
  AuthenticatedProjectsProjectIdMembersRoute:
    AuthenticatedProjectsProjectIdMembersRoute,
  AuthenticatedProjectsProjectIdSecretsRoute:
    AuthenticatedProjectsProjectIdSecretsRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedWorkflowsWorkflowIdRequestsRouteChildren {
  AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute: typeof AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute
}

const AuthenticatedWorkflowsWorkflowIdRequestsRouteChildren: AuthenticatedWorkflowsWorkflowIdRequestsRouteChildren =
  {
    AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute:
      AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute,
  }

const AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren =
  AuthenticatedWorkflowsWorkflowIdRequestsRoute._addFileChildren(
    AuthenticatedWorkflowsWorkflowIdRequestsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgentProfilesRoute: typeof AuthenticatedAgentProfilesRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAuthProvidersRoute: typeof AuthenticatedAuthProvidersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAdminSecretsRoute: typeof AuthenticatedAdminSecretsRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
  AuthenticatedWorkflowsWorkflowIdEditRoute: typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  AuthenticatedWorkflowsWorkflowIdRequestsRoute: typeof AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren
  AuthenticatedAdminGroupsIndexRoute: typeof AuthenticatedAdminGroupsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentProfilesRoute: AuthenticatedAgentProfilesRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAuthProvidersRoute: AuthenticatedAuthProvidersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAdminSecretsRoute: AuthenticatedAdminSecretsRoute,
  AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
  AuthenticatedWorkflowsWorkflowIdEditRoute:
    AuthenticatedWorkflowsWorkflowIdEditRoute,
  AuthenticatedWorkflowsWorkflowIdRequestsRoute:
    AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren,
  AuthenticatedAdminGroupsIndexRoute: AuthenticatedAdminGroupsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
