/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedMyWorkRouteImport } from './routes/_authenticated/my-work'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuthProvidersRouteImport } from './routes/_authenticated/auth-providers'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAgentProfilesRouteImport } from './routes/_authenticated/agent-profiles'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'
import { Route as AuthenticatedAssistantsIndexRouteImport } from './routes/_authenticated/assistants/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedPlatformSecurityRouteImport } from './routes/_authenticated/platform/security'
import { Route as AuthenticatedPlatformAiInfraRouteImport } from './routes/_authenticated/platform/ai-infra'
import { Route as AuthenticatedPlatformAiContextRouteImport } from './routes/_authenticated/platform/ai-context'
import { Route as AuthenticatedAdminSecretsRouteImport } from './routes/_authenticated/admin/secrets'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin/providers'
import { Route as AuthenticatedPlatformConnectionsIndexRouteImport } from './routes/_authenticated/platform/connections/index'
import { Route as AuthenticatedAdminGroupsIndexRouteImport } from './routes/_authenticated/admin/groups/index'
import { Route as AuthenticatedWorkflowsWorkflowIdRequestsRouteImport } from './routes/_authenticated/workflows/$workflowId.requests'
import { Route as AuthenticatedWorkflowsWorkflowIdEditRouteImport } from './routes/_authenticated/workflows/$workflowId.edit'
import { Route as AuthenticatedProjectsProjectIdSecretsRouteImport } from './routes/_authenticated/projects/$projectId.secrets'
import { Route as AuthenticatedProjectsProjectIdMembersRouteImport } from './routes/_authenticated/projects/$projectId.members'
import { Route as AuthenticatedProjectsProjectIdChatRouteImport } from './routes/_authenticated/projects/$projectId.chat'
import { Route as AuthenticatedProjectsProjectIdAiContextRouteImport } from './routes/_authenticated/projects/$projectId.ai-context'
import { Route as AuthenticatedPlatformSecuritySecretsRouteImport } from './routes/_authenticated/platform/security/secrets'
import { Route as AuthenticatedPlatformSecurityAuthProvidersRouteImport } from './routes/_authenticated/platform/security/auth-providers'
import { Route as AuthenticatedPlatformConnectionsIdRouteImport } from './routes/_authenticated/platform/connections/$id'
import { Route as AuthenticatedPlatformAiInfraToolsRouteImport } from './routes/_authenticated/platform/ai-infra/tools'
import { Route as AuthenticatedPlatformAiInfraProvidersRouteImport } from './routes/_authenticated/platform/ai-infra/providers'
import { Route as AuthenticatedPlatformAiInfraModelsRouteImport } from './routes/_authenticated/platform/ai-infra/models'
import { Route as AuthenticatedPlatformAiInfraAgentsRouteImport } from './routes/_authenticated/platform/ai-infra/agents'
import { Route as AuthenticatedPlatformAiInfraAgentProfilesRouteImport } from './routes/_authenticated/platform/ai-infra/agent-profiles'
import { Route as AuthenticatedPlatformAiContextGovernanceProfileRouteImport } from './routes/_authenticated/platform/ai-context/governance-profile'
import { Route as AuthenticatedAssistantsAssistantIdEditRouteImport } from './routes/_authenticated/assistants/$assistantId.edit'
import { Route as AuthenticatedPlatformAiContextKnowledgeSourcesIndexRouteImport } from './routes/_authenticated/platform/ai-context/knowledge-sources/index'
import { Route as AuthenticatedPlatformAiContextKnowledgeProvidersIndexRouteImport } from './routes/_authenticated/platform/ai-context/knowledge-providers/index'
import { Route as AuthenticatedPlatformAiContextInstructionAssetsIndexRouteImport } from './routes/_authenticated/platform/ai-context/instruction-assets/index'
import { Route as AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRouteImport } from './routes/_authenticated/workflows/$workflowId.requests.$requestId'
import { Route as AuthenticatedProjectsProjectIdKnowledgeProvidersIdRouteImport } from './routes/_authenticated/projects/$projectId/knowledge-providers/$id'
import { Route as AuthenticatedProjectsProjectIdInstructionAssetsIdRouteImport } from './routes/_authenticated/projects/$projectId/instruction-assets/$id'
import { Route as AuthenticatedPlatformAiContextKnowledgeSourcesIdRouteImport } from './routes/_authenticated/platform/ai-context/knowledge-sources/$id'
import { Route as AuthenticatedPlatformAiContextKnowledgeProvidersIdRouteImport } from './routes/_authenticated/platform/ai-context/knowledge-providers/$id'
import { Route as AuthenticatedPlatformAiContextInstructionAssetsIdRouteImport } from './routes/_authenticated/platform/ai-context/instruction-assets/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyWorkRoute = AuthenticatedMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthProvidersRoute =
  AuthenticatedAuthProvidersRouteImport.update({
    id: '/auth-providers',
    path: '/auth-providers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentProfilesRoute =
  AuthenticatedAgentProfilesRouteImport.update({
    id: '/agent-profiles',
    path: '/agent-profiles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedAssistantsIndexRoute =
  AuthenticatedAssistantsIndexRouteImport.update({
    id: '/assistants/',
    path: '/assistants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedPlatformSecurityRoute =
  AuthenticatedPlatformSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformAiInfraRoute =
  AuthenticatedPlatformAiInfraRouteImport.update({
    id: '/ai-infra',
    path: '/ai-infra',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformAiContextRoute =
  AuthenticatedPlatformAiContextRouteImport.update({
    id: '/ai-context',
    path: '/ai-context',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedAdminSecretsRoute =
  AuthenticatedAdminSecretsRouteImport.update({
    id: '/admin/secrets',
    path: '/admin/secrets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/admin/providers',
    path: '/admin/providers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformConnectionsIndexRoute =
  AuthenticatedPlatformConnectionsIndexRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedAdminGroupsIndexRoute =
  AuthenticatedAdminGroupsIndexRouteImport.update({
    id: '/admin/groups/',
    path: '/admin/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsWorkflowIdRequestsRoute =
  AuthenticatedWorkflowsWorkflowIdRequestsRouteImport.update({
    id: '/workflows/$workflowId/requests',
    path: '/workflows/$workflowId/requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsWorkflowIdEditRoute =
  AuthenticatedWorkflowsWorkflowIdEditRouteImport.update({
    id: '/workflows/$workflowId/edit',
    path: '/workflows/$workflowId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdSecretsRoute =
  AuthenticatedProjectsProjectIdSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMembersRoute =
  AuthenticatedProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdChatRoute =
  AuthenticatedProjectsProjectIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdAiContextRoute =
  AuthenticatedProjectsProjectIdAiContextRouteImport.update({
    id: '/ai-context',
    path: '/ai-context',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedPlatformSecuritySecretsRoute =
  AuthenticatedPlatformSecuritySecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => AuthenticatedPlatformSecurityRoute,
  } as any)
const AuthenticatedPlatformSecurityAuthProvidersRoute =
  AuthenticatedPlatformSecurityAuthProvidersRouteImport.update({
    id: '/auth-providers',
    path: '/auth-providers',
    getParentRoute: () => AuthenticatedPlatformSecurityRoute,
  } as any)
const AuthenticatedPlatformConnectionsIdRoute =
  AuthenticatedPlatformConnectionsIdRouteImport.update({
    id: '/connections/$id',
    path: '/connections/$id',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformAiInfraToolsRoute =
  AuthenticatedPlatformAiInfraToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => AuthenticatedPlatformAiInfraRoute,
  } as any)
const AuthenticatedPlatformAiInfraProvidersRoute =
  AuthenticatedPlatformAiInfraProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedPlatformAiInfraRoute,
  } as any)
const AuthenticatedPlatformAiInfraModelsRoute =
  AuthenticatedPlatformAiInfraModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => AuthenticatedPlatformAiInfraRoute,
  } as any)
const AuthenticatedPlatformAiInfraAgentsRoute =
  AuthenticatedPlatformAiInfraAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedPlatformAiInfraRoute,
  } as any)
const AuthenticatedPlatformAiInfraAgentProfilesRoute =
  AuthenticatedPlatformAiInfraAgentProfilesRouteImport.update({
    id: '/agent-profiles',
    path: '/agent-profiles',
    getParentRoute: () => AuthenticatedPlatformAiInfraRoute,
  } as any)
const AuthenticatedPlatformAiContextGovernanceProfileRoute =
  AuthenticatedPlatformAiContextGovernanceProfileRouteImport.update({
    id: '/governance-profile',
    path: '/governance-profile',
    getParentRoute: () => AuthenticatedPlatformAiContextRoute,
  } as any)
const AuthenticatedAssistantsAssistantIdEditRoute =
  AuthenticatedAssistantsAssistantIdEditRouteImport.update({
    id: '/assistants/$assistantId/edit',
    path: '/assistants/$assistantId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformAiContextKnowledgeSourcesIndexRoute =
  AuthenticatedPlatformAiContextKnowledgeSourcesIndexRouteImport.update({
    id: '/knowledge-sources/',
    path: '/knowledge-sources/',
    getParentRoute: () => AuthenticatedPlatformAiContextRoute,
  } as any)
const AuthenticatedPlatformAiContextKnowledgeProvidersIndexRoute =
  AuthenticatedPlatformAiContextKnowledgeProvidersIndexRouteImport.update({
    id: '/knowledge-providers/',
    path: '/knowledge-providers/',
    getParentRoute: () => AuthenticatedPlatformAiContextRoute,
  } as any)
const AuthenticatedPlatformAiContextInstructionAssetsIndexRoute =
  AuthenticatedPlatformAiContextInstructionAssetsIndexRouteImport.update({
    id: '/instruction-assets/',
    path: '/instruction-assets/',
    getParentRoute: () => AuthenticatedPlatformAiContextRoute,
  } as any)
const AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute =
  AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => AuthenticatedWorkflowsWorkflowIdRequestsRoute,
  } as any)
const AuthenticatedProjectsProjectIdKnowledgeProvidersIdRoute =
  AuthenticatedProjectsProjectIdKnowledgeProvidersIdRouteImport.update({
    id: '/knowledge-providers/$id',
    path: '/knowledge-providers/$id',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdInstructionAssetsIdRoute =
  AuthenticatedProjectsProjectIdInstructionAssetsIdRouteImport.update({
    id: '/instruction-assets/$id',
    path: '/instruction-assets/$id',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedPlatformAiContextKnowledgeSourcesIdRoute =
  AuthenticatedPlatformAiContextKnowledgeSourcesIdRouteImport.update({
    id: '/knowledge-sources/$id',
    path: '/knowledge-sources/$id',
    getParentRoute: () => AuthenticatedPlatformAiContextRoute,
  } as any)
const AuthenticatedPlatformAiContextKnowledgeProvidersIdRoute =
  AuthenticatedPlatformAiContextKnowledgeProvidersIdRouteImport.update({
    id: '/knowledge-providers/$id',
    path: '/knowledge-providers/$id',
    getParentRoute: () => AuthenticatedPlatformAiContextRoute,
  } as any)
const AuthenticatedPlatformAiContextInstructionAssetsIdRoute =
  AuthenticatedPlatformAiContextInstructionAssetsIdRouteImport.update({
    id: '/instruction-assets/$id',
    path: '/instruction-assets/$id',
    getParentRoute: () => AuthenticatedPlatformAiContextRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent-profiles': typeof AuthenticatedAgentProfilesRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/auth-providers': typeof AuthenticatedAuthProvidersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/models': typeof AuthenticatedModelsRoute
  '/my-work': typeof AuthenticatedMyWorkRoute
  '/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/tools': typeof AuthenticatedToolsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/secrets': typeof AuthenticatedAdminSecretsRoute
  '/platform/ai-context': typeof AuthenticatedPlatformAiContextRouteWithChildren
  '/platform/ai-infra': typeof AuthenticatedPlatformAiInfraRouteWithChildren
  '/platform/security': typeof AuthenticatedPlatformSecurityRouteWithChildren
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/assistants/': typeof AuthenticatedAssistantsIndexRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/assistants/$assistantId/edit': typeof AuthenticatedAssistantsAssistantIdEditRoute
  '/platform/ai-context/governance-profile': typeof AuthenticatedPlatformAiContextGovernanceProfileRoute
  '/platform/ai-infra/agent-profiles': typeof AuthenticatedPlatformAiInfraAgentProfilesRoute
  '/platform/ai-infra/agents': typeof AuthenticatedPlatformAiInfraAgentsRoute
  '/platform/ai-infra/models': typeof AuthenticatedPlatformAiInfraModelsRoute
  '/platform/ai-infra/providers': typeof AuthenticatedPlatformAiInfraProvidersRoute
  '/platform/ai-infra/tools': typeof AuthenticatedPlatformAiInfraToolsRoute
  '/platform/connections/$id': typeof AuthenticatedPlatformConnectionsIdRoute
  '/platform/security/auth-providers': typeof AuthenticatedPlatformSecurityAuthProvidersRoute
  '/platform/security/secrets': typeof AuthenticatedPlatformSecuritySecretsRoute
  '/projects/$projectId/ai-context': typeof AuthenticatedProjectsProjectIdAiContextRoute
  '/projects/$projectId/chat': typeof AuthenticatedProjectsProjectIdChatRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/secrets': typeof AuthenticatedProjectsProjectIdSecretsRoute
  '/workflows/$workflowId/edit': typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  '/workflows/$workflowId/requests': typeof AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren
  '/admin/groups/': typeof AuthenticatedAdminGroupsIndexRoute
  '/platform/connections/': typeof AuthenticatedPlatformConnectionsIndexRoute
  '/platform/ai-context/instruction-assets/$id': typeof AuthenticatedPlatformAiContextInstructionAssetsIdRoute
  '/platform/ai-context/knowledge-providers/$id': typeof AuthenticatedPlatformAiContextKnowledgeProvidersIdRoute
  '/platform/ai-context/knowledge-sources/$id': typeof AuthenticatedPlatformAiContextKnowledgeSourcesIdRoute
  '/projects/$projectId/instruction-assets/$id': typeof AuthenticatedProjectsProjectIdInstructionAssetsIdRoute
  '/projects/$projectId/knowledge-providers/$id': typeof AuthenticatedProjectsProjectIdKnowledgeProvidersIdRoute
  '/workflows/$workflowId/requests/$requestId': typeof AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute
  '/platform/ai-context/instruction-assets/': typeof AuthenticatedPlatformAiContextInstructionAssetsIndexRoute
  '/platform/ai-context/knowledge-providers/': typeof AuthenticatedPlatformAiContextKnowledgeProvidersIndexRoute
  '/platform/ai-context/knowledge-sources/': typeof AuthenticatedPlatformAiContextKnowledgeSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent-profiles': typeof AuthenticatedAgentProfilesRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/auth-providers': typeof AuthenticatedAuthProvidersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/models': typeof AuthenticatedModelsRoute
  '/my-work': typeof AuthenticatedMyWorkRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/tools': typeof AuthenticatedToolsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/secrets': typeof AuthenticatedAdminSecretsRoute
  '/platform/ai-context': typeof AuthenticatedPlatformAiContextRouteWithChildren
  '/platform/ai-infra': typeof AuthenticatedPlatformAiInfraRouteWithChildren
  '/platform/security': typeof AuthenticatedPlatformSecurityRouteWithChildren
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/assistants': typeof AuthenticatedAssistantsIndexRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/assistants/$assistantId/edit': typeof AuthenticatedAssistantsAssistantIdEditRoute
  '/platform/ai-context/governance-profile': typeof AuthenticatedPlatformAiContextGovernanceProfileRoute
  '/platform/ai-infra/agent-profiles': typeof AuthenticatedPlatformAiInfraAgentProfilesRoute
  '/platform/ai-infra/agents': typeof AuthenticatedPlatformAiInfraAgentsRoute
  '/platform/ai-infra/models': typeof AuthenticatedPlatformAiInfraModelsRoute
  '/platform/ai-infra/providers': typeof AuthenticatedPlatformAiInfraProvidersRoute
  '/platform/ai-infra/tools': typeof AuthenticatedPlatformAiInfraToolsRoute
  '/platform/connections/$id': typeof AuthenticatedPlatformConnectionsIdRoute
  '/platform/security/auth-providers': typeof AuthenticatedPlatformSecurityAuthProvidersRoute
  '/platform/security/secrets': typeof AuthenticatedPlatformSecuritySecretsRoute
  '/projects/$projectId/ai-context': typeof AuthenticatedProjectsProjectIdAiContextRoute
  '/projects/$projectId/chat': typeof AuthenticatedProjectsProjectIdChatRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/secrets': typeof AuthenticatedProjectsProjectIdSecretsRoute
  '/workflows/$workflowId/edit': typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  '/workflows/$workflowId/requests': typeof AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren
  '/admin/groups': typeof AuthenticatedAdminGroupsIndexRoute
  '/platform/connections': typeof AuthenticatedPlatformConnectionsIndexRoute
  '/platform/ai-context/instruction-assets/$id': typeof AuthenticatedPlatformAiContextInstructionAssetsIdRoute
  '/platform/ai-context/knowledge-providers/$id': typeof AuthenticatedPlatformAiContextKnowledgeProvidersIdRoute
  '/platform/ai-context/knowledge-sources/$id': typeof AuthenticatedPlatformAiContextKnowledgeSourcesIdRoute
  '/projects/$projectId/instruction-assets/$id': typeof AuthenticatedProjectsProjectIdInstructionAssetsIdRoute
  '/projects/$projectId/knowledge-providers/$id': typeof AuthenticatedProjectsProjectIdKnowledgeProvidersIdRoute
  '/workflows/$workflowId/requests/$requestId': typeof AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute
  '/platform/ai-context/instruction-assets': typeof AuthenticatedPlatformAiContextInstructionAssetsIndexRoute
  '/platform/ai-context/knowledge-providers': typeof AuthenticatedPlatformAiContextKnowledgeProvidersIndexRoute
  '/platform/ai-context/knowledge-sources': typeof AuthenticatedPlatformAiContextKnowledgeSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agent-profiles': typeof AuthenticatedAgentProfilesRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/auth-providers': typeof AuthenticatedAuthProvidersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/my-work': typeof AuthenticatedMyWorkRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/admin/secrets': typeof AuthenticatedAdminSecretsRoute
  '/_authenticated/platform/ai-context': typeof AuthenticatedPlatformAiContextRouteWithChildren
  '/_authenticated/platform/ai-infra': typeof AuthenticatedPlatformAiInfraRouteWithChildren
  '/_authenticated/platform/security': typeof AuthenticatedPlatformSecurityRouteWithChildren
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/assistants/': typeof AuthenticatedAssistantsIndexRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/_authenticated/assistants/$assistantId/edit': typeof AuthenticatedAssistantsAssistantIdEditRoute
  '/_authenticated/platform/ai-context/governance-profile': typeof AuthenticatedPlatformAiContextGovernanceProfileRoute
  '/_authenticated/platform/ai-infra/agent-profiles': typeof AuthenticatedPlatformAiInfraAgentProfilesRoute
  '/_authenticated/platform/ai-infra/agents': typeof AuthenticatedPlatformAiInfraAgentsRoute
  '/_authenticated/platform/ai-infra/models': typeof AuthenticatedPlatformAiInfraModelsRoute
  '/_authenticated/platform/ai-infra/providers': typeof AuthenticatedPlatformAiInfraProvidersRoute
  '/_authenticated/platform/ai-infra/tools': typeof AuthenticatedPlatformAiInfraToolsRoute
  '/_authenticated/platform/connections/$id': typeof AuthenticatedPlatformConnectionsIdRoute
  '/_authenticated/platform/security/auth-providers': typeof AuthenticatedPlatformSecurityAuthProvidersRoute
  '/_authenticated/platform/security/secrets': typeof AuthenticatedPlatformSecuritySecretsRoute
  '/_authenticated/projects/$projectId/ai-context': typeof AuthenticatedProjectsProjectIdAiContextRoute
  '/_authenticated/projects/$projectId/chat': typeof AuthenticatedProjectsProjectIdChatRoute
  '/_authenticated/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/_authenticated/projects/$projectId/secrets': typeof AuthenticatedProjectsProjectIdSecretsRoute
  '/_authenticated/workflows/$workflowId/edit': typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  '/_authenticated/workflows/$workflowId/requests': typeof AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren
  '/_authenticated/admin/groups/': typeof AuthenticatedAdminGroupsIndexRoute
  '/_authenticated/platform/connections/': typeof AuthenticatedPlatformConnectionsIndexRoute
  '/_authenticated/platform/ai-context/instruction-assets/$id': typeof AuthenticatedPlatformAiContextInstructionAssetsIdRoute
  '/_authenticated/platform/ai-context/knowledge-providers/$id': typeof AuthenticatedPlatformAiContextKnowledgeProvidersIdRoute
  '/_authenticated/platform/ai-context/knowledge-sources/$id': typeof AuthenticatedPlatformAiContextKnowledgeSourcesIdRoute
  '/_authenticated/projects/$projectId/instruction-assets/$id': typeof AuthenticatedProjectsProjectIdInstructionAssetsIdRoute
  '/_authenticated/projects/$projectId/knowledge-providers/$id': typeof AuthenticatedProjectsProjectIdKnowledgeProvidersIdRoute
  '/_authenticated/workflows/$workflowId/requests/$requestId': typeof AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute
  '/_authenticated/platform/ai-context/instruction-assets/': typeof AuthenticatedPlatformAiContextInstructionAssetsIndexRoute
  '/_authenticated/platform/ai-context/knowledge-providers/': typeof AuthenticatedPlatformAiContextKnowledgeProvidersIndexRoute
  '/_authenticated/platform/ai-context/knowledge-sources/': typeof AuthenticatedPlatformAiContextKnowledgeSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agent-profiles'
    | '/agents'
    | '/auth-providers'
    | '/dashboard'
    | '/models'
    | '/my-work'
    | '/platform'
    | '/projects'
    | '/tools'
    | '/users'
    | '/admin/providers'
    | '/admin/secrets'
    | '/platform/ai-context'
    | '/platform/ai-infra'
    | '/platform/security'
    | '/projects/$projectId'
    | '/assistants/'
    | '/platform/'
    | '/workflows/'
    | '/assistants/$assistantId/edit'
    | '/platform/ai-context/governance-profile'
    | '/platform/ai-infra/agent-profiles'
    | '/platform/ai-infra/agents'
    | '/platform/ai-infra/models'
    | '/platform/ai-infra/providers'
    | '/platform/ai-infra/tools'
    | '/platform/connections/$id'
    | '/platform/security/auth-providers'
    | '/platform/security/secrets'
    | '/projects/$projectId/ai-context'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/members'
    | '/projects/$projectId/secrets'
    | '/workflows/$workflowId/edit'
    | '/workflows/$workflowId/requests'
    | '/admin/groups/'
    | '/platform/connections/'
    | '/platform/ai-context/instruction-assets/$id'
    | '/platform/ai-context/knowledge-providers/$id'
    | '/platform/ai-context/knowledge-sources/$id'
    | '/projects/$projectId/instruction-assets/$id'
    | '/projects/$projectId/knowledge-providers/$id'
    | '/workflows/$workflowId/requests/$requestId'
    | '/platform/ai-context/instruction-assets/'
    | '/platform/ai-context/knowledge-providers/'
    | '/platform/ai-context/knowledge-sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agent-profiles'
    | '/agents'
    | '/auth-providers'
    | '/dashboard'
    | '/models'
    | '/my-work'
    | '/projects'
    | '/tools'
    | '/users'
    | '/admin/providers'
    | '/admin/secrets'
    | '/platform/ai-context'
    | '/platform/ai-infra'
    | '/platform/security'
    | '/projects/$projectId'
    | '/assistants'
    | '/platform'
    | '/workflows'
    | '/assistants/$assistantId/edit'
    | '/platform/ai-context/governance-profile'
    | '/platform/ai-infra/agent-profiles'
    | '/platform/ai-infra/agents'
    | '/platform/ai-infra/models'
    | '/platform/ai-infra/providers'
    | '/platform/ai-infra/tools'
    | '/platform/connections/$id'
    | '/platform/security/auth-providers'
    | '/platform/security/secrets'
    | '/projects/$projectId/ai-context'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/members'
    | '/projects/$projectId/secrets'
    | '/workflows/$workflowId/edit'
    | '/workflows/$workflowId/requests'
    | '/admin/groups'
    | '/platform/connections'
    | '/platform/ai-context/instruction-assets/$id'
    | '/platform/ai-context/knowledge-providers/$id'
    | '/platform/ai-context/knowledge-sources/$id'
    | '/projects/$projectId/instruction-assets/$id'
    | '/projects/$projectId/knowledge-providers/$id'
    | '/workflows/$workflowId/requests/$requestId'
    | '/platform/ai-context/instruction-assets'
    | '/platform/ai-context/knowledge-providers'
    | '/platform/ai-context/knowledge-sources'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agent-profiles'
    | '/_authenticated/agents'
    | '/_authenticated/auth-providers'
    | '/_authenticated/dashboard'
    | '/_authenticated/models'
    | '/_authenticated/my-work'
    | '/_authenticated/platform'
    | '/_authenticated/projects'
    | '/_authenticated/tools'
    | '/_authenticated/users'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/secrets'
    | '/_authenticated/platform/ai-context'
    | '/_authenticated/platform/ai-infra'
    | '/_authenticated/platform/security'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/assistants/'
    | '/_authenticated/platform/'
    | '/_authenticated/workflows/'
    | '/_authenticated/assistants/$assistantId/edit'
    | '/_authenticated/platform/ai-context/governance-profile'
    | '/_authenticated/platform/ai-infra/agent-profiles'
    | '/_authenticated/platform/ai-infra/agents'
    | '/_authenticated/platform/ai-infra/models'
    | '/_authenticated/platform/ai-infra/providers'
    | '/_authenticated/platform/ai-infra/tools'
    | '/_authenticated/platform/connections/$id'
    | '/_authenticated/platform/security/auth-providers'
    | '/_authenticated/platform/security/secrets'
    | '/_authenticated/projects/$projectId/ai-context'
    | '/_authenticated/projects/$projectId/chat'
    | '/_authenticated/projects/$projectId/members'
    | '/_authenticated/projects/$projectId/secrets'
    | '/_authenticated/workflows/$workflowId/edit'
    | '/_authenticated/workflows/$workflowId/requests'
    | '/_authenticated/admin/groups/'
    | '/_authenticated/platform/connections/'
    | '/_authenticated/platform/ai-context/instruction-assets/$id'
    | '/_authenticated/platform/ai-context/knowledge-providers/$id'
    | '/_authenticated/platform/ai-context/knowledge-sources/$id'
    | '/_authenticated/projects/$projectId/instruction-assets/$id'
    | '/_authenticated/projects/$projectId/knowledge-providers/$id'
    | '/_authenticated/workflows/$workflowId/requests/$requestId'
    | '/_authenticated/platform/ai-context/instruction-assets/'
    | '/_authenticated/platform/ai-context/knowledge-providers/'
    | '/_authenticated/platform/ai-context/knowledge-sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-work': {
      id: '/_authenticated/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof AuthenticatedMyWorkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auth-providers': {
      id: '/_authenticated/auth-providers'
      path: '/auth-providers'
      fullPath: '/auth-providers'
      preLoaderRoute: typeof AuthenticatedAuthProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-profiles': {
      id: '/_authenticated/agent-profiles'
      path: '/agent-profiles'
      fullPath: '/agent-profiles'
      preLoaderRoute: typeof AuthenticatedAgentProfilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/assistants/': {
      id: '/_authenticated/assistants/'
      path: '/assistants'
      fullPath: '/assistants/'
      preLoaderRoute: typeof AuthenticatedAssistantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/platform/security': {
      id: '/_authenticated/platform/security'
      path: '/security'
      fullPath: '/platform/security'
      preLoaderRoute: typeof AuthenticatedPlatformSecurityRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/ai-infra': {
      id: '/_authenticated/platform/ai-infra'
      path: '/ai-infra'
      fullPath: '/platform/ai-infra'
      preLoaderRoute: typeof AuthenticatedPlatformAiInfraRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/ai-context': {
      id: '/_authenticated/platform/ai-context'
      path: '/ai-context'
      fullPath: '/platform/ai-context'
      preLoaderRoute: typeof AuthenticatedPlatformAiContextRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/admin/secrets': {
      id: '/_authenticated/admin/secrets'
      path: '/admin/secrets'
      fullPath: '/admin/secrets'
      preLoaderRoute: typeof AuthenticatedAdminSecretsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/connections/': {
      id: '/_authenticated/platform/connections/'
      path: '/connections'
      fullPath: '/platform/connections/'
      preLoaderRoute: typeof AuthenticatedPlatformConnectionsIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/admin/groups/': {
      id: '/_authenticated/admin/groups/'
      path: '/admin/groups'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AuthenticatedAdminGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/$workflowId/requests': {
      id: '/_authenticated/workflows/$workflowId/requests'
      path: '/workflows/$workflowId/requests'
      fullPath: '/workflows/$workflowId/requests'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/$workflowId/edit': {
      id: '/_authenticated/workflows/$workflowId/edit'
      path: '/workflows/$workflowId/edit'
      fullPath: '/workflows/$workflowId/edit'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/secrets': {
      id: '/_authenticated/projects/$projectId/secrets'
      path: '/secrets'
      fullPath: '/projects/$projectId/secrets'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSecretsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/members': {
      id: '/_authenticated/projects/$projectId/members'
      path: '/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMembersRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/chat': {
      id: '/_authenticated/projects/$projectId/chat'
      path: '/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdChatRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/ai-context': {
      id: '/_authenticated/projects/$projectId/ai-context'
      path: '/ai-context'
      fullPath: '/projects/$projectId/ai-context'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAiContextRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/platform/security/secrets': {
      id: '/_authenticated/platform/security/secrets'
      path: '/secrets'
      fullPath: '/platform/security/secrets'
      preLoaderRoute: typeof AuthenticatedPlatformSecuritySecretsRouteImport
      parentRoute: typeof AuthenticatedPlatformSecurityRoute
    }
    '/_authenticated/platform/security/auth-providers': {
      id: '/_authenticated/platform/security/auth-providers'
      path: '/auth-providers'
      fullPath: '/platform/security/auth-providers'
      preLoaderRoute: typeof AuthenticatedPlatformSecurityAuthProvidersRouteImport
      parentRoute: typeof AuthenticatedPlatformSecurityRoute
    }
    '/_authenticated/platform/connections/$id': {
      id: '/_authenticated/platform/connections/$id'
      path: '/connections/$id'
      fullPath: '/platform/connections/$id'
      preLoaderRoute: typeof AuthenticatedPlatformConnectionsIdRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/ai-infra/tools': {
      id: '/_authenticated/platform/ai-infra/tools'
      path: '/tools'
      fullPath: '/platform/ai-infra/tools'
      preLoaderRoute: typeof AuthenticatedPlatformAiInfraToolsRouteImport
      parentRoute: typeof AuthenticatedPlatformAiInfraRoute
    }
    '/_authenticated/platform/ai-infra/providers': {
      id: '/_authenticated/platform/ai-infra/providers'
      path: '/providers'
      fullPath: '/platform/ai-infra/providers'
      preLoaderRoute: typeof AuthenticatedPlatformAiInfraProvidersRouteImport
      parentRoute: typeof AuthenticatedPlatformAiInfraRoute
    }
    '/_authenticated/platform/ai-infra/models': {
      id: '/_authenticated/platform/ai-infra/models'
      path: '/models'
      fullPath: '/platform/ai-infra/models'
      preLoaderRoute: typeof AuthenticatedPlatformAiInfraModelsRouteImport
      parentRoute: typeof AuthenticatedPlatformAiInfraRoute
    }
    '/_authenticated/platform/ai-infra/agents': {
      id: '/_authenticated/platform/ai-infra/agents'
      path: '/agents'
      fullPath: '/platform/ai-infra/agents'
      preLoaderRoute: typeof AuthenticatedPlatformAiInfraAgentsRouteImport
      parentRoute: typeof AuthenticatedPlatformAiInfraRoute
    }
    '/_authenticated/platform/ai-infra/agent-profiles': {
      id: '/_authenticated/platform/ai-infra/agent-profiles'
      path: '/agent-profiles'
      fullPath: '/platform/ai-infra/agent-profiles'
      preLoaderRoute: typeof AuthenticatedPlatformAiInfraAgentProfilesRouteImport
      parentRoute: typeof AuthenticatedPlatformAiInfraRoute
    }
    '/_authenticated/platform/ai-context/governance-profile': {
      id: '/_authenticated/platform/ai-context/governance-profile'
      path: '/governance-profile'
      fullPath: '/platform/ai-context/governance-profile'
      preLoaderRoute: typeof AuthenticatedPlatformAiContextGovernanceProfileRouteImport
      parentRoute: typeof AuthenticatedPlatformAiContextRoute
    }
    '/_authenticated/assistants/$assistantId/edit': {
      id: '/_authenticated/assistants/$assistantId/edit'
      path: '/assistants/$assistantId/edit'
      fullPath: '/assistants/$assistantId/edit'
      preLoaderRoute: typeof AuthenticatedAssistantsAssistantIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/ai-context/knowledge-sources/': {
      id: '/_authenticated/platform/ai-context/knowledge-sources/'
      path: '/knowledge-sources'
      fullPath: '/platform/ai-context/knowledge-sources/'
      preLoaderRoute: typeof AuthenticatedPlatformAiContextKnowledgeSourcesIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformAiContextRoute
    }
    '/_authenticated/platform/ai-context/knowledge-providers/': {
      id: '/_authenticated/platform/ai-context/knowledge-providers/'
      path: '/knowledge-providers'
      fullPath: '/platform/ai-context/knowledge-providers/'
      preLoaderRoute: typeof AuthenticatedPlatformAiContextKnowledgeProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformAiContextRoute
    }
    '/_authenticated/platform/ai-context/instruction-assets/': {
      id: '/_authenticated/platform/ai-context/instruction-assets/'
      path: '/instruction-assets'
      fullPath: '/platform/ai-context/instruction-assets/'
      preLoaderRoute: typeof AuthenticatedPlatformAiContextInstructionAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformAiContextRoute
    }
    '/_authenticated/workflows/$workflowId/requests/$requestId': {
      id: '/_authenticated/workflows/$workflowId/requests/$requestId'
      path: '/$requestId'
      fullPath: '/workflows/$workflowId/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedWorkflowsWorkflowIdRequestsRoute
    }
    '/_authenticated/projects/$projectId/knowledge-providers/$id': {
      id: '/_authenticated/projects/$projectId/knowledge-providers/$id'
      path: '/knowledge-providers/$id'
      fullPath: '/projects/$projectId/knowledge-providers/$id'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdKnowledgeProvidersIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/instruction-assets/$id': {
      id: '/_authenticated/projects/$projectId/instruction-assets/$id'
      path: '/instruction-assets/$id'
      fullPath: '/projects/$projectId/instruction-assets/$id'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdInstructionAssetsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/platform/ai-context/knowledge-sources/$id': {
      id: '/_authenticated/platform/ai-context/knowledge-sources/$id'
      path: '/knowledge-sources/$id'
      fullPath: '/platform/ai-context/knowledge-sources/$id'
      preLoaderRoute: typeof AuthenticatedPlatformAiContextKnowledgeSourcesIdRouteImport
      parentRoute: typeof AuthenticatedPlatformAiContextRoute
    }
    '/_authenticated/platform/ai-context/knowledge-providers/$id': {
      id: '/_authenticated/platform/ai-context/knowledge-providers/$id'
      path: '/knowledge-providers/$id'
      fullPath: '/platform/ai-context/knowledge-providers/$id'
      preLoaderRoute: typeof AuthenticatedPlatformAiContextKnowledgeProvidersIdRouteImport
      parentRoute: typeof AuthenticatedPlatformAiContextRoute
    }
    '/_authenticated/platform/ai-context/instruction-assets/$id': {
      id: '/_authenticated/platform/ai-context/instruction-assets/$id'
      path: '/instruction-assets/$id'
      fullPath: '/platform/ai-context/instruction-assets/$id'
      preLoaderRoute: typeof AuthenticatedPlatformAiContextInstructionAssetsIdRouteImport
      parentRoute: typeof AuthenticatedPlatformAiContextRoute
    }
  }
}

interface AuthenticatedPlatformAiContextRouteChildren {
  AuthenticatedPlatformAiContextGovernanceProfileRoute: typeof AuthenticatedPlatformAiContextGovernanceProfileRoute
  AuthenticatedPlatformAiContextInstructionAssetsIdRoute: typeof AuthenticatedPlatformAiContextInstructionAssetsIdRoute
  AuthenticatedPlatformAiContextKnowledgeProvidersIdRoute: typeof AuthenticatedPlatformAiContextKnowledgeProvidersIdRoute
  AuthenticatedPlatformAiContextKnowledgeSourcesIdRoute: typeof AuthenticatedPlatformAiContextKnowledgeSourcesIdRoute
  AuthenticatedPlatformAiContextInstructionAssetsIndexRoute: typeof AuthenticatedPlatformAiContextInstructionAssetsIndexRoute
  AuthenticatedPlatformAiContextKnowledgeProvidersIndexRoute: typeof AuthenticatedPlatformAiContextKnowledgeProvidersIndexRoute
  AuthenticatedPlatformAiContextKnowledgeSourcesIndexRoute: typeof AuthenticatedPlatformAiContextKnowledgeSourcesIndexRoute
}

const AuthenticatedPlatformAiContextRouteChildren: AuthenticatedPlatformAiContextRouteChildren =
  {
    AuthenticatedPlatformAiContextGovernanceProfileRoute:
      AuthenticatedPlatformAiContextGovernanceProfileRoute,
    AuthenticatedPlatformAiContextInstructionAssetsIdRoute:
      AuthenticatedPlatformAiContextInstructionAssetsIdRoute,
    AuthenticatedPlatformAiContextKnowledgeProvidersIdRoute:
      AuthenticatedPlatformAiContextKnowledgeProvidersIdRoute,
    AuthenticatedPlatformAiContextKnowledgeSourcesIdRoute:
      AuthenticatedPlatformAiContextKnowledgeSourcesIdRoute,
    AuthenticatedPlatformAiContextInstructionAssetsIndexRoute:
      AuthenticatedPlatformAiContextInstructionAssetsIndexRoute,
    AuthenticatedPlatformAiContextKnowledgeProvidersIndexRoute:
      AuthenticatedPlatformAiContextKnowledgeProvidersIndexRoute,
    AuthenticatedPlatformAiContextKnowledgeSourcesIndexRoute:
      AuthenticatedPlatformAiContextKnowledgeSourcesIndexRoute,
  }

const AuthenticatedPlatformAiContextRouteWithChildren =
  AuthenticatedPlatformAiContextRoute._addFileChildren(
    AuthenticatedPlatformAiContextRouteChildren,
  )

interface AuthenticatedPlatformAiInfraRouteChildren {
  AuthenticatedPlatformAiInfraAgentProfilesRoute: typeof AuthenticatedPlatformAiInfraAgentProfilesRoute
  AuthenticatedPlatformAiInfraAgentsRoute: typeof AuthenticatedPlatformAiInfraAgentsRoute
  AuthenticatedPlatformAiInfraModelsRoute: typeof AuthenticatedPlatformAiInfraModelsRoute
  AuthenticatedPlatformAiInfraProvidersRoute: typeof AuthenticatedPlatformAiInfraProvidersRoute
  AuthenticatedPlatformAiInfraToolsRoute: typeof AuthenticatedPlatformAiInfraToolsRoute
}

const AuthenticatedPlatformAiInfraRouteChildren: AuthenticatedPlatformAiInfraRouteChildren =
  {
    AuthenticatedPlatformAiInfraAgentProfilesRoute:
      AuthenticatedPlatformAiInfraAgentProfilesRoute,
    AuthenticatedPlatformAiInfraAgentsRoute:
      AuthenticatedPlatformAiInfraAgentsRoute,
    AuthenticatedPlatformAiInfraModelsRoute:
      AuthenticatedPlatformAiInfraModelsRoute,
    AuthenticatedPlatformAiInfraProvidersRoute:
      AuthenticatedPlatformAiInfraProvidersRoute,
    AuthenticatedPlatformAiInfraToolsRoute:
      AuthenticatedPlatformAiInfraToolsRoute,
  }

const AuthenticatedPlatformAiInfraRouteWithChildren =
  AuthenticatedPlatformAiInfraRoute._addFileChildren(
    AuthenticatedPlatformAiInfraRouteChildren,
  )

interface AuthenticatedPlatformSecurityRouteChildren {
  AuthenticatedPlatformSecurityAuthProvidersRoute: typeof AuthenticatedPlatformSecurityAuthProvidersRoute
  AuthenticatedPlatformSecuritySecretsRoute: typeof AuthenticatedPlatformSecuritySecretsRoute
}

const AuthenticatedPlatformSecurityRouteChildren: AuthenticatedPlatformSecurityRouteChildren =
  {
    AuthenticatedPlatformSecurityAuthProvidersRoute:
      AuthenticatedPlatformSecurityAuthProvidersRoute,
    AuthenticatedPlatformSecuritySecretsRoute:
      AuthenticatedPlatformSecuritySecretsRoute,
  }

const AuthenticatedPlatformSecurityRouteWithChildren =
  AuthenticatedPlatformSecurityRoute._addFileChildren(
    AuthenticatedPlatformSecurityRouteChildren,
  )

interface AuthenticatedPlatformRouteChildren {
  AuthenticatedPlatformAiContextRoute: typeof AuthenticatedPlatformAiContextRouteWithChildren
  AuthenticatedPlatformAiInfraRoute: typeof AuthenticatedPlatformAiInfraRouteWithChildren
  AuthenticatedPlatformSecurityRoute: typeof AuthenticatedPlatformSecurityRouteWithChildren
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
  AuthenticatedPlatformConnectionsIdRoute: typeof AuthenticatedPlatformConnectionsIdRoute
  AuthenticatedPlatformConnectionsIndexRoute: typeof AuthenticatedPlatformConnectionsIndexRoute
}

const AuthenticatedPlatformRouteChildren: AuthenticatedPlatformRouteChildren = {
  AuthenticatedPlatformAiContextRoute:
    AuthenticatedPlatformAiContextRouteWithChildren,
  AuthenticatedPlatformAiInfraRoute:
    AuthenticatedPlatformAiInfraRouteWithChildren,
  AuthenticatedPlatformSecurityRoute:
    AuthenticatedPlatformSecurityRouteWithChildren,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
  AuthenticatedPlatformConnectionsIdRoute:
    AuthenticatedPlatformConnectionsIdRoute,
  AuthenticatedPlatformConnectionsIndexRoute:
    AuthenticatedPlatformConnectionsIndexRoute,
}

const AuthenticatedPlatformRouteWithChildren =
  AuthenticatedPlatformRoute._addFileChildren(
    AuthenticatedPlatformRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdAiContextRoute: typeof AuthenticatedProjectsProjectIdAiContextRoute
  AuthenticatedProjectsProjectIdChatRoute: typeof AuthenticatedProjectsProjectIdChatRoute
  AuthenticatedProjectsProjectIdMembersRoute: typeof AuthenticatedProjectsProjectIdMembersRoute
  AuthenticatedProjectsProjectIdSecretsRoute: typeof AuthenticatedProjectsProjectIdSecretsRoute
  AuthenticatedProjectsProjectIdInstructionAssetsIdRoute: typeof AuthenticatedProjectsProjectIdInstructionAssetsIdRoute
  AuthenticatedProjectsProjectIdKnowledgeProvidersIdRoute: typeof AuthenticatedProjectsProjectIdKnowledgeProvidersIdRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdAiContextRoute:
      AuthenticatedProjectsProjectIdAiContextRoute,
    AuthenticatedProjectsProjectIdChatRoute:
      AuthenticatedProjectsProjectIdChatRoute,
    AuthenticatedProjectsProjectIdMembersRoute:
      AuthenticatedProjectsProjectIdMembersRoute,
    AuthenticatedProjectsProjectIdSecretsRoute:
      AuthenticatedProjectsProjectIdSecretsRoute,
    AuthenticatedProjectsProjectIdInstructionAssetsIdRoute:
      AuthenticatedProjectsProjectIdInstructionAssetsIdRoute,
    AuthenticatedProjectsProjectIdKnowledgeProvidersIdRoute:
      AuthenticatedProjectsProjectIdKnowledgeProvidersIdRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedWorkflowsWorkflowIdRequestsRouteChildren {
  AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute: typeof AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute
}

const AuthenticatedWorkflowsWorkflowIdRequestsRouteChildren: AuthenticatedWorkflowsWorkflowIdRequestsRouteChildren =
  {
    AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute:
      AuthenticatedWorkflowsWorkflowIdRequestsRequestIdRoute,
  }

const AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren =
  AuthenticatedWorkflowsWorkflowIdRequestsRoute._addFileChildren(
    AuthenticatedWorkflowsWorkflowIdRequestsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgentProfilesRoute: typeof AuthenticatedAgentProfilesRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAuthProvidersRoute: typeof AuthenticatedAuthProvidersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedMyWorkRoute: typeof AuthenticatedMyWorkRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRouteWithChildren
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminSecretsRoute: typeof AuthenticatedAdminSecretsRoute
  AuthenticatedAssistantsIndexRoute: typeof AuthenticatedAssistantsIndexRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
  AuthenticatedAssistantsAssistantIdEditRoute: typeof AuthenticatedAssistantsAssistantIdEditRoute
  AuthenticatedWorkflowsWorkflowIdEditRoute: typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  AuthenticatedWorkflowsWorkflowIdRequestsRoute: typeof AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren
  AuthenticatedAdminGroupsIndexRoute: typeof AuthenticatedAdminGroupsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentProfilesRoute: AuthenticatedAgentProfilesRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAuthProvidersRoute: AuthenticatedAuthProvidersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedMyWorkRoute: AuthenticatedMyWorkRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRouteWithChildren,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
  AuthenticatedAdminSecretsRoute: AuthenticatedAdminSecretsRoute,
  AuthenticatedAssistantsIndexRoute: AuthenticatedAssistantsIndexRoute,
  AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
  AuthenticatedAssistantsAssistantIdEditRoute:
    AuthenticatedAssistantsAssistantIdEditRoute,
  AuthenticatedWorkflowsWorkflowIdEditRoute:
    AuthenticatedWorkflowsWorkflowIdEditRoute,
  AuthenticatedWorkflowsWorkflowIdRequestsRoute:
    AuthenticatedWorkflowsWorkflowIdRequestsRouteWithChildren,
  AuthenticatedAdminGroupsIndexRoute: AuthenticatedAdminGroupsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
